name: cosmic
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1

  cloud_firestore: ^6.0.0
  bloc: ^9.0.0
  meta: ^1.16.0
  equatable: ^2.0.7
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
