// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__Qyr-Wwi0V4jqv_a3neK6zFAjh0ROeQ',
    appId: '1:94383412361:web:223cd21e6c89d6a8e46258',
    messagingSenderId: '94383412361',
    projectId: 'cosmic-9c396',
    authDomain: 'cosmic-9c396.firebaseapp.com',
    storageBucket: 'cosmic-9c396.firebasestorage.app',
    measurementId: 'G-2F6GJBELYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6Ny7_ScPvoLYtjNpA7g0_cAOqI64ZaE',
    appId: '1:94383412361:android:8a9c9b81176a0671e46258',
    messagingSenderId: '94383412361',
    projectId: 'cosmic-9c396',
    storageBucket: 'cosmic-9c396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQVRbEBCjX-T9bFO3TEpHOzdWJzm7OQ4I',
    appId: '1:94383412361:ios:e33feeb735243dbae46258',
    messagingSenderId: '94383412361',
    projectId: 'cosmic-9c396',
    storageBucket: 'cosmic-9c396.firebasestorage.app',
    iosBundleId: 'com.example.cosmic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQVRbEBCjX-T9bFO3TEpHOzdWJzm7OQ4I',
    appId: '1:94383412361:ios:e33feeb735243dbae46258',
    messagingSenderId: '94383412361',
    projectId: 'cosmic-9c396',
    storageBucket: 'cosmic-9c396.firebasestorage.app',
    iosBundleId: 'com.example.cosmic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD__Qyr-Wwi0V4jqv_a3neK6zFAjh0ROeQ',
    appId: '1:94383412361:web:659ae46bbcc7ed2ce46258',
    messagingSenderId: '94383412361',
    projectId: 'cosmic-9c396',
    authDomain: 'cosmic-9c396.firebaseapp.com',
    storageBucket: 'cosmic-9c396.firebasestorage.app',
    measurementId: 'G-FC7VLYPQFL',
  );
}
